import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'fr_FR': {
      // Home Page
      'Oasis Eclat Inc': 'Oasis Eclat Inc',
      'Reset All Payments': 'Réinitialiser tous les paiements',
      'Delete All Customers': 'Supprimer tous les clients',
      'Schedule All Reminders': 'Planifier tous les rappels',
      'Search customers...': 'Rechercher des clients...',
      'Service Type': 'Type de service',
      'Upcoming Services': 'Services à venir',
      'customers': 'clients',
      'No customers found': 'Aucun client trouvé',
      'Try adjusting your filters or add a new customer': 'Essayez d\'ajuster vos filtres ou ajoutez un nouveau client',

      // Customer Card
      'Edit Customer': 'Modifier le client',
      'Test Notification': 'Tester la notification',
      'Delete Customer': 'Supprimer le client',
      'Success': 'Succès',
      'Customer updated successfully': 'Client mis à jour avec succès',
      'Service marked as cleaned!': 'Service marqué comme nettoyé!',
      'Service marked as not Cleaned!': 'Service marqué comme non nettoyé!',
      'Nettoyer': 'Nettoyer',
      'En Attente': 'En Attente',

      // Customer Stats Card
      'Total': 'Total',
      'Nettoyer': 'Nettoyer',
      'En Attente': 'En Attente',

      // Edit Customer Form
      'Edit Customer': 'Modifier le client',
      'Customer Name': 'Nom du client',
      'Enter customer name': 'Entrez le nom du client',
      'Please enter the customer name': 'Veuillez entrer le nom du client',
      'Customer name must be at least 2 characters': 'Le nom du client doit comporter au moins 2 caractères',
      'Service': 'Service',
      'e.g., Residential Cleaning': 'ex. Nettoyage résidentiel',
      'Please enter the service type': 'Veuillez entrer le type de service',
      'Phone Number': 'Numéro de téléphone',
      'e.g., +1 234 567 8900': 'ex. +1 234 567 8900',
      'Please enter the phone number': 'Veuillez entrer le numéro de téléphone',
      'Please enter a valid phone number': 'Veuillez entrer un numéro de téléphone valide',
      'Address': 'Adresse',
      'Enter service address': 'Entrez l\'adresse du service',
      'Please enter the service address': 'Veuillez entrer l\'adresse du service',
      'Amount to be Paid': 'Montant à payer',
      'e.g., 150.00': 'ex. 150,00',
      'Please enter the amount': 'Veuillez entrer le montant',
      'Please enter a valid amount': 'Veuillez entrer un montant valide',
      'Amount must be greater than 0': 'Le montant doit être supérieur à 0',
      'Service Date & Time': 'Date et heure du service',
      'Payment Status': 'Statut de paiement',
      'Cleaned': 'Nettoyé',
      'UnCleaned': 'Non nettoyé',
      'Update Customer': 'Mettre à jour le client',
      'Cancel': 'Annuler',

      // Add Customer Form
      'Add Customer': 'Ajouter un client',
      'Nom du client': 'Nom du client',
      'Entrez le nom du client': 'Entrez le nom du client',
      'e.g., Nettoyage Residentielle': 'ex. Nettoyage résidentiel',
      'Entrez le type de service': 'Entrez le type de service',
      'Numeros de telephone': 'Numéros de téléphone',
      'Status de Nettoyage': 'Statut de nettoyage',
      'Nettoyer': 'Nettoyer',
      'En Ettente': 'En Attente',
      'Ajouter': 'Ajouter',
      'Annuler': 'Annuler',

      // Home Controller
      'Failed to load customers': 'Échec du chargement des clients',
      'Customer added successfully!': 'Client ajouté avec succès!',
      'Failed to add customer': 'Échec de l\'ajout du client',
      'Failed to update customer': 'Échec de la mise à jour du client',
      'Failed to update cleaning status': 'Échec de la mise à jour du statut de nettoyage',
      'Reset All Services': 'Réinitialiser tous les services',
      'Are you sure you want to mark all customers as NotCleaned?': 'Êtes-vous sûr de vouloir marquer tous les clients comme non nettoyés?',
      'All payments reset to notCleaned!': 'Tous les paiements réinitialisés à non nettoyés!',
      'Failed to reset payment statuses': 'Échec de la réinitialisation des statuts de paiement',
      'Test notification sent for': 'Notification de test envoyée pour',
      'Failed to send test notification': 'Échec de l\'envoi de la notification de test',
      'Notifications scheduled for all customers!': 'Notifications planifiées pour tous les clients!',
      'Failed to schedule notifications': 'Échec de la planification des notifications',
      'All notifications cancelled!': 'Toutes les notifications annulées!',
      'Failed to cancel notifications': 'Échec de l\'annulation des notifications',
      'Error': 'Erreur',
      'Info': 'Information',
    },


    'en_US': {
      // Home Page
      'Oasis Eclat Inc': 'Oasis Eclat Inc',
      'Reset All Payments': 'Reset All Payments',
      'Delete All Customers': 'Delete All Customers',
      'Schedule All Reminders': 'Schedule All Reminders',
      'Search customers...': 'Search customers...',
      'Service Type': 'Service Type',
      'Upcoming Services': 'Upcoming Services',
      'customers': 'customers',
      'No customers found': 'No customers found',
      'Try adjusting your filters or add a new customer': 'Try adjusting your filters or add a new customer',

      // Customer Card
      'Edit Customer': 'Edit Customer',
      'Test Notification': 'Test Notification',
      'Delete Customer': 'Delete Customer',
      'Success': 'Success',
      'Customer updated successfully': 'Customer updated successfully',
      'Service marked as cleaned!': 'Service marked as cleaned!',
      'Service marked as not Cleaned!': 'Service marked as not Cleaned!',
      'Nettoyer': 'Cleaned',
      'En Attente': 'Pending',

      // Customer Stats Card
      'Total': 'Total',
      'Nettoyer': 'Cleaned',
      'En Attente': 'Pending',

      // Edit Customer Form
      'Edit Customer': 'Edit Customer',
      'Customer Name': 'Customer Name',
      'Enter customer name': 'Enter customer name',
      'Please enter the customer name': 'Please enter the customer name',
      'Customer name must be at least 2 characters': 'Customer name must be at least 2 characters',
      'Service': 'Service',
      'e.g., Residential Cleaning': 'e.g., Residential Cleaning',
      'Please enter the service type': 'Please enter the service type',
      'Phone Number': 'Phone Number',
      'e.g., +1 234 567 8900': 'e.g., +1 234 567 8900',
      'Please enter the phone number': 'Please enter the phone number',
      'Please enter a valid phone number': 'Please enter a valid phone number',
      'Address': 'Address',
      'Enter service address': 'Enter service address',
      'Please enter the service address': 'Please enter the service address',
      'Amount to be Paid': 'Amount to be Paid',
      'e.g., 150.00': 'e.g., 150.00',
      'Please enter the amount': 'Please enter the amount',
      'Please enter a valid amount': 'Please enter a valid amount',
      'Amount must be greater than 0': 'Amount must be greater than 0',
      'Service Date & Time': 'Service Date & Time',
      'Payment Status': 'Payment Status',
      'Cleaned': 'Cleaned',
      'UnCleaned': 'UnCleaned',
      'Update Customer': 'Update Customer',
      'Cancel': 'Cancel',

      // Add Customer Form
      'Add Customer': 'Add Customer',
      'Nom du client': 'Customer Name',
      'Entrez le nom du client': 'Enter customer name',
      'e.g., Nettoyage Residentielle': 'e.g., Residential Cleaning',
      'Entrez le type de service': 'Enter service type',
      'Numeros de telephone': 'Phone Number',
      'Status de Nettoyage': 'Cleaning Status',
      'Nettoyer': 'Cleaned',
      'En Ettente': 'Pending',
      'Ajouter': 'Add',
      'Annuler': 'Cancel',

      // Home Controller
      'Failed to load customers': 'Failed to load customers',
      'Customer added successfully!': 'Customer added successfully!',
      'Failed to add customer': 'Failed to add customer',
      'Failed to update customer': 'Failed to update customer',
      'Failed to update cleaning status': 'Failed to update cleaning status',
      'Reset All Services': 'Reset All Services',
      'Are you sure you want to mark all customers as NotCleaned?': 'Are you sure you want to mark all customers as NotCleaned?',
      'All payments reset to notCleaned!': 'All payments reset to notCleaned!',
      'Failed to reset payment statuses': 'Failed to reset payment statuses',
      'Test notification sent for': 'Test notification sent for',
      'Failed to send test notification': 'Failed to send test notification',
      'Notifications scheduled for all customers!': 'Notifications scheduled for all customers!',
      'Failed to schedule notifications': 'Failed to schedule notifications',
      'All notifications cancelled!': 'All notifications cancelled!',
      'Failed to cancel notifications': 'Failed to cancel notifications',
      'Error': 'Error',
      'Info': 'Info',
    }
  };
}